version: '3.7'

services:
  postgres2:
    image: postgres:15
    container_name: vtb-postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pagila
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./01-pagila-schema.sql:/docker-entrypoint-initdb.d/01-pagila-schema.sql
      - ./02-pagila-insert-data.sql:/docker-entrypoint-initdb.d/02-pagila-insert-data.sql
      - ./03-init-readonly.sql:/docker-entrypoint-initdb.d/03-init-readonly.sql
    restart: always
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

volumes:
  postgres_data2:
    driver: local
